//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswers
    {
        public int QuestionAnswerID { get; set; }
        public Nullable<int> SectionQuestionID { get; set; }
        public string AnswerText { get; set; }
    
        public virtual SectionQuestions SectionQuestions { get; set; }
    }
}
