//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectionQuestions()
        {
            this.QuestionAnswers = new HashSet<QuestionAnswers>();
        }
    
        public int SectionQuestionID { get; set; }
        public Nullable<int> CourseSectionID { get; set; }
        public string QuestionText { get; set; }
        public string CorrectAnswer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionAnswers> QuestionAnswers { get; set; }
    }
}
