//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
    }
}
